### ISSUE TITLE
Beta Testing & Deployment Checklist

### ISSUE THREAD

**Issue by TechSolomon** [jbonda/ml-workflow-pipeline#46]
Tester: @TAWinterton2 
- [x] Python: https://devguide.python.org/versions/
- [x] Branch management: `dev` vs. `main`
- [ ] Redirect: [404 Not Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404)
- [ ] #59
    - [ ] #44 
- [ ] Error message
    - [x] Invalid file
      - [x] #52 
    - [x] All/none testing & training
    - [x] Remove debug outputs
- [ ] Duplicate rows on files without headers
- [x] Full dataset viewing for large files (size limit)
    - [x] #40
